namespace ClashLand.Logic.Enums
{
    public enum Gamefile
    {
        None = 0,
        Buildings = 1,
        Locales = 2,
        Resources = 3,
        Characters = 4,
        Animations = 5,
        Projectiles = 6,
        Building_Classes = 7,
        Obstacles = 8,
        Effects = 9,
        Particle_Emitters = 10,
        Experience_Levels = 11,
        Traps = 12,
        Alliance_Badges = 13,
        Globals = 14,
        Townhall_Levels = 15,
        Alliance_Portal = 16,
        Npcs = 17,
        Decos = 18,
        Resource_Packs = 19,
        Shields = 20,
        Missions = 21,
        Billing_Packages = 22,
        Achievements = 23,
        Credits = 24,
        Faq = 25,
        Spells = 26,
        Hints = 27,
        Heroes = 28,
        Leagues = 29,
        News = 30,
        War = 31,
        Regions = 32,
        Client_Globals = 33,
        Alliance_Badge_Layers = 34,
        Alliance_Levels = 35,
        Helpshift = 36,
        Variables = 37,
        Gem_Bundles = 38,
        Village_Objects = 39,
        Calendar_Event_Functions = 40,
        Boombox = 41,
        Event_Entries = 42,
        Deeplinks = 43,
        Leagues2 = 44,
    }
}
